#!/usr/bin/env bash
#
# sambuca :: engine/maintenance/backup.sh
#
# Encrypted backup of everything that cannot be re-derived from the repository:
# databases, application state, secrets and configuration.
#
# ══════════════════════════════════════════════════════════════════════════
# THE ONE THING THIS SCRIPT EXISTS TO GET RIGHT
#
# restic exits 3 on "some files could not be read" — a PARTIAL backup. A wrapper
# that tests `if restic backup; then echo OK` treats 3 as failure but many treat
# only non-zero-except-3 as failure, or worse, ignore the code entirely. Both
# mistakes produce a backup log that says "done OK" over a snapshot missing most
# of the data, and nobody finds out until a restore.
#
# So: exit codes are handled EXPLICITLY, 3 is a LOUD WARNING with the file
# count, and the run is verified by reading back a snapshot — never by trusting
# the exit code alone.
# ══════════════════════════════════════════════════════════════════════════
#
# The repository password is derived from the 24-word seed phrase generated by
# the flasher and printed on the recovery document. That is what makes the paper
# sufficient for disaster recovery: the seed reconstructs the repository key
# even if this machine is ash.
#
set -uo pipefail

SB_TAG="backup"
_SB_SELF_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=engine/lib/common.sh
source "${_SB_SELF_DIR}/../lib/common.sh"
sb_trap_err

sb_require_root
sb_single_instance "backup" 30
sb_require restic

# shellcheck source=/dev/null
for f in provision.env storage.env backup.env; do
    [[ -r "${SB_ETC}/${f}" ]] && source "${SB_ETC}/${f}"
done

: "${SAMBUCA_DATA:=/srv/sambuca}"
: "${RESTIC_REPOSITORY:=${SAMBUCA_DATA}/backups/restic}"
: "${SAMBUCA_BACKUP_RETENTION_DAILY:=7}"
: "${SAMBUCA_BACKUP_RETENTION_WEEKLY:=4}"
: "${SAMBUCA_BACKUP_RETENTION_MONTHLY:=12}"

PW_FILE="${SB_ETC}/secrets/restic_password"
[[ -s $PW_FILE ]] || die "no restic password at ${PW_FILE} — run: sambuca-backup init"
export RESTIC_REPOSITORY RESTIC_PASSWORD_FILE="$PW_FILE"

COMPOSE_DIR="${SAMBUCA_COMPOSE_DIR:-/opt/sambuca/compose}"
DUMP_DIR="${SB_LIB}/dumps"
install -d -m 0700 "$DUMP_DIR"

# ---------------------------------------------------------------------------
# 1. Consistent database dumps.
#
# Copying a live Postgres data directory produces a file set that restores into
# a corrupt cluster often enough to be worthless. Dump first, back up the dump.
# ---------------------------------------------------------------------------
dump_postgres() {
    local container="$1" user="$2" db="$3"
    local out="${DUMP_DIR}/${db}.sql.zst"

    docker inspect -f '{{.State.Running}}' "$container" 2>/dev/null | grep -qx true || {
        log "skip ${db}: container ${container} is not running"
        return 0
    }

    log "dumping ${db} from ${container}"
    if docker exec "$container" pg_dump -U "$user" -d "$db" --clean --if-exists \
        2>"${SB_LOG_DIR}/dump-${db}.err" | zstd -q -19 -T0 -o "${out}.tmp" 2>/dev/null; then
        mv -f -- "${out}.tmp" "$out"
        chmod 0600 -- "$out"
        ok "${db}: $(du -h "$out" | cut -f1) dumped"
        return 0
    fi

    rm -f -- "${out}.tmp"
    err "${db}: pg_dump FAILED — $(tail -n2 "${SB_LOG_DIR}/dump-${db}.err" | tr '\n' ' ')"
    return 1
}

dump_failures=0
dump_postgres sambuca-immich-db  immich  immich  || ((dump_failures++))
dump_postgres sambuca-blinko-db  blinko  blinko  || ((dump_failures++))
dump_postgres sambuca-synapse-db synapse synapse || ((dump_failures++))

# Vaultwarden's sqlite needs the online-backup API, not a file copy.
if docker inspect -f '{{.State.Running}}' sambuca-vaultwarden >/dev/null 2>&1; then
    if docker exec sambuca-vaultwarden \
        sqlite3 /data/db.sqlite3 ".backup '/data/db-backup.sqlite3'" 2>/dev/null; then
        ok "vaultwarden: sqlite online backup taken"
    else
        warn "vaultwarden: sqlite online backup failed — the raw file will be captured instead"
        ((dump_failures++))
    fi
fi

((dump_failures > 0)) && warn "${dump_failures} database dump(s) failed — the snapshot will be INCOMPLETE"

# ---------------------------------------------------------------------------
# 2. Repository init (first run only)
# ---------------------------------------------------------------------------
if ! restic cat config >/dev/null 2>&1; then
    log "initialising restic repository at ${RESTIC_REPOSITORY}"
    restic init || die "restic init failed"
fi

# ---------------------------------------------------------------------------
# 3. The backup itself
# ---------------------------------------------------------------------------
TARGETS=(
    "${SB_ETC}"                       # config + secrets
    "${DUMP_DIR}"                     # database dumps
    "${SAMBUCA_DATA}/appdata"         # application state
    "${SAMBUCA_DATA}/files"           # user documents
    "${SAMBUCA_DATA}/photos"          # user photos
)
EXCLUDES=(
    --exclude "${SAMBUCA_DATA}/backups"                # never back up the repo into itself
    --exclude "**/postgres/**"                         # captured as dumps above
    --exclude "**/redis/**"                            # ephemeral cache
    --exclude "**/model-cache/**"                      # re-downloadable
    --exclude "**/ollama/models/**"                    # re-downloadable, and huge
    --exclude "**/caddy/data/caddy/locks/**"
    --exclude "*.tmp"
    --exclude "**/lost+found"
)

existing=()
for t in "${TARGETS[@]}"; do
    [[ -e $t ]] && existing+=("$t") || warn "backup target missing, skipping: ${t}"
done
((${#existing[@]} > 0)) || die "no backup targets exist — nothing to do"

log "backing up ${#existing[@]} target(s) to ${RESTIC_REPOSITORY}"
set +e
restic backup \
    --tag sambuca --tag "tier${SAMBUCA_TIER:-0}" \
    --host "$(hostname)" \
    "${EXCLUDES[@]}" \
    "${existing[@]}" \
    >"${SB_LOG_DIR}/restic-backup.out" 2>&1
rc=$?
set -e

# ── the exit-code handling this whole script is built around ──
case $rc in
    0)
        ok "backup completed with no errors"
        ;;
    3)
        # PARTIAL. Not a success. Name the files, do not bury it in a log.
        err "═══════════════════════════════════════════════════════════════"
        err " BACKUP IS INCOMPLETE (restic exit 3): some files were unreadable."
        err " This snapshot EXISTS but does NOT contain everything you asked for."
        err "═══════════════════════════════════════════════════════════════"
        grep -iE "error|permission|denied|unable" "${SB_LOG_DIR}/restic-backup.out" \
            | head -n 20 | while read -r l; do err "  ${l}"; done
        n="$(grep -ciE "error|unable" "${SB_LOG_DIR}/restic-backup.out" || echo '?')"
        err "  ${n} error line(s) total — full log: ${SB_LOG_DIR}/restic-backup.out"
        ;;
    *)
        err "backup FAILED (restic exit ${rc})"
        tail -n 20 "${SB_LOG_DIR}/restic-backup.out" | while read -r l; do err "  ${l}"; done
        die "no usable snapshot was produced"
        ;;
esac

# ---------------------------------------------------------------------------
# 4. VERIFY BY READING BACK. The exit code is a claim; this is evidence.
# ---------------------------------------------------------------------------
snap_id="$(restic snapshots --json --latest 1 2>/dev/null | jq -r '.[0].short_id // empty' || true)"
[[ -n $snap_id ]] || die "no snapshot found after backup — the repository is not what it claims"

file_count="$(restic ls "$snap_id" 2>/dev/null | wc -l || echo 0)"
log "snapshot ${snap_id} contains ${file_count} path(s)"

if ((file_count < 10)); then
    err "snapshot ${snap_id} contains only ${file_count} paths — that is not a real backup"
    err "  This is the failure mode where a wrapper reports success over 17 of 966 files."
    exit 1
fi

# Restore one known file to a scratch dir and compare. A repository that lists
# files but cannot produce their contents is a repository you find out about
# during a disaster.
verify_dir="$(mktemp -d)"
# shellcheck disable=SC2064
trap "rm -rf -- '${verify_dir}'" EXIT
if restic restore "$snap_id" --target "$verify_dir" --include "${SB_ETC}/profile.env" >/dev/null 2>&1 \
   && [[ -s "${verify_dir}${SB_ETC}/profile.env" ]]; then
    ok "restore verification PASSED (${SB_ETC}/profile.env round-tripped)"
else
    err "restore verification FAILED — the snapshot lists files it cannot produce"
    exit 1
fi

# ---------------------------------------------------------------------------
# 5. Retention.
#
# `forget` marks; `prune` deletes. Pruning is a destructive, non-atomic
# operation on the one copy of your data, so it is OPT-IN and off by default.
# ---------------------------------------------------------------------------
log "applying retention policy"
restic forget \
    --keep-daily "$SAMBUCA_BACKUP_RETENTION_DAILY" \
    --keep-weekly "$SAMBUCA_BACKUP_RETENTION_WEEKLY" \
    --keep-monthly "$SAMBUCA_BACKUP_RETENTION_MONTHLY" \
    --tag sambuca \
    >>"${SB_LOG_DIR}/restic-backup.out" 2>&1 \
    || warn "restic forget reported errors"

if [[ ${SAMBUCA_BACKUP_PRUNE:-0} == 1 ]]; then
    log "pruning (SAMBUCA_BACKUP_PRUNE=1)"
    restic prune --max-unused 10% >>"${SB_LOG_DIR}/restic-backup.out" 2>&1 \
        || warn "restic prune reported errors"
else
    log "prune skipped (set SAMBUCA_BACKUP_PRUNE=1 in ${SB_ETC}/backup.env to enable)"
fi

# ---------------------------------------------------------------------------
# 6. State for the monitoring layer.
# ---------------------------------------------------------------------------
{
    printf '{\n'
    printf '  "last_run": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '  "exit_code": %d,\n' "$rc"
    printf '  "status": "%s",\n' "$([[ $rc == 0 ]] && echo ok || echo partial)"
    printf '  "snapshot": "%s",\n' "$snap_id"
    printf '  "paths": %d,\n' "$file_count"
    printf '  "restore_verified": true,\n'
    printf '  "repository": "%s"\n' "$RESTIC_REPOSITORY"
    printf '}\n'
} | sb_atomic_write "${SB_LIB}/backup-state.json" 0644

[[ $rc == 0 ]] && ok "backup ${snap_id} verified" || warn "backup ${snap_id} verified but INCOMPLETE"
exit "$([[ $rc == 0 ]] && echo 0 || echo 3)"
